# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination basted on number of posts
#exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh'] # files to exclude
markdown: redcarpet
highligher: pygments
